kind: Project
name: kaptal
apiVersion: garden.io/v1
environments:
  - name: local
    defaultNamespace: default
    variables:
      base-hostname: local.app.garden
providers:
  - name: local-kubernetes
    environment: [local]
    context: docker-desktop
